### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by XhmikosR**
Still haven't been able to try your tool but thought I'd share a few stuff.
1. Added JSHint support
2. Added Travis CI support
3. Added badges in README.md
4. Added missing properties in package.json

### CODE REVIEW

**Comment by Venemo** [comment]
@XhmikosR You are awesome! Thanks for helping me with this.

**Comment by XhmikosR** [comment]
No problem, glad I could help. 

Don't forget to enable the Travis CI in the repository settings.

**Comment by Venemo** [comment]
@XhmikosR What exactly is Travis CI? I've never used it before.

**Comment by XhmikosR** [comment]
You can check it in action in clean-css' repository for example.  It runs tests for each commit, pull request etc. I forgot to properly enable it for css-fitness, I'll make a pull request later.

**Pull request merged**
